export const loading_constants = [
    "🧠 Waking up... give me a sec, my brain's still loading.",
    "☕ Brewing virtual coffee before we start cooking.",
    "⚡ Charging brain cells to 100%...",
    "🚀 Spinning things up... this won't take long.",
    "💻 Setting up the workspace for today's chaos.",
    "📦 Unboxing fresh ideas...",
    "🔌 Plugging into the matrix... don't pull the cable.",
    "✨ Summoning a few million parameters...",
    "🛠️ Tightening a few loose screws...",
    "🎯 Getting locked in...",
    "👀 Looking productive already...",
    "🔥 Entering cook mode...",
    "🤖 Teaching JavaScript who's in charge...",
    "📡 Connecting to the AI brain...",
    "🎨 Making the terminal look cooler than it needs to.",
    "😤 Locking in... distractions are cancelled.",
    "🧩 Assembling pixels, prompts and questionable life choices.",
    "🌌 Aligning the coding universe...",
    "🪄 Adding a tiny bit of developer magic...",
    "🚧 Building today's masterpiece... hopefully."
  ];

  export const greeting_constants = [
    "👋 Yo! Good to see you again.",
    "🚀 Say less. Let's build.",
    "🔥 Cook mode activated.",
    "😤 Lock in. We've got work to do.",
    "⚡ Ready when you are.",
    "💻 Workspace secured.",
    "✨ What's the move today?",
    "🧠 Brain online. Ideas welcome.",
    "🎯 Time to ship.",
    "🤝 Welcome back.",
    "🚧 Let's build something people remember.",
    "👀 So... what are we cooking today?",
    "🔥 Another day, another commit.",
    "💡 Every big project starts with one prompt.",
    "⚡ Everything's ready. Your move.",
    "🚀 Let's make GitHub proud.",
    "😎 Back again? I like that.",
    "💻 Ctrl + S is your best friend.",
    "🛠️ Time to build, not overthink.",
    "🌙 Late night coding hits different.",
    "☕ Coffee loaded. Brain loading complete.",
    "🤖 Your AI coding buddy is online.",
    "✨ Small idea. Big build.",
    "🎉 Let's turn ideas into reality.",
    "📦 Workspace loaded successfully.",
    "🔥 Today's the day we ship.",
    "⚡ Time to make the keyboard suffer.",
    "💭 What's today's crazy idea?",
    "🎯 Let's build first, optimize later.",
    "🚀 One command closer to greatness.",
    "🧩 Everything's in place. Let's go.",
    "😮‍💨 Deep breath... now code.",
    "👨‍💻 The terminal missed you.",
    "⚙️ Systems online. Chaos accepted.",
    "🔥 Ready to break things... and fix them.",
    "💻 Ship now. Sleep later.",
    "✨ Let's make today's commit count.",
    "🚀 Build. Debug. Repeat.",
    "😤 We don't quit. We deploy.",
    "👀 Alright... impress me."
  ];

  export const default_ai_messages= [
    "👋 Hey! What's on your mind today?",
    "🚀 Alright, what are we building?",
    "💭 Throw me your best question.",
    "⚡ I'm all ears. What's up?",
    "🎯 Let's solve something interesting.",
    "🤝 Good to see you! What's today's mission?",
    "💻 Got an idea? Let's explore it.",
    "🔥 What's the first challenge?",
    "🧠 Ready whenever you are.",
    "✨ Ask me anything.",
    "🚀 Let's turn ideas into reality.",
    "👀 What's today's rabbit hole?",
    "🎨 Building, debugging or brainstorming?",
    "🛠️ What are we working on today?",
    "💡 Every great project starts with a question.",
    "😎 Hit me with it.",
    "⚡ What's the move?",
    "🌌 Curious about something?",
    "🚧 Let's figure it out together.",
    "☕ Coffee's ready. What's next?"
  ];

  export const thinking_messages = [
    "🧠 Thinking...",
    "💭 Connecting the dots...",
    "⚡ Processing...",
    "🤔 One sec...",
    "📚 Looking into it...",
    "🚀 Thinking at terminal speed...",
    "🔍 Digging deeper...",
    "🛠️ Putting the pieces together...",
    "✨ Almost there...",
    "👀 Looking into it..."
  ];